### ISSUE TITLE
Add support to define custom annotations to the Deployment

### ISSUE THREAD

**Issue by subigre** [konateq/ehrbase-helm-chart#11]
There might be some use cases use cases that require defining annotations on the `Deployment` resource.

An example of such a case is the use of [stakater/Reloader](https://github.com/stakater/Reloader) to automatically restart pods when some `ConfigMap`/`Secrets` resources change:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehrbase
  namespace: ehrbase
  annotations:
    secret.reloader.stakater.com/reload: "ehrbase-users-secret,ehrbase-tls-secret"
    configmap.reloader.stakater.com/reload: "ehrbase-configuration,ehrbase-env-vars"
```
