### ISSUE TITLE
Enable end-to-end TLS 

### ISSUE THREAD

**Issue by subigre** [konateq/ehrbase-helm-chart#5]
Support configuration to run EHRbase pod(s) using HTTPS 

```yaml
tls:
  enabled: true
  # ...
```
